services:
  mysql:
    image: mysql:8.0
    container_name: paylock-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: paylock
      MYSQL_USER: paylock
      MYSQL_PASSWORD: paylock
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - paylock-network

  paylock:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/paylock?sslMode=DISABLED
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: password
      APP_JWT_SECRET: "9hucogN6halWRWBSZ4TRLEAIzRhucogN6haaSyCAHs1nlWR_1nlWRucogN6ha1nk2j"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep -q '\"status\":\"UP\"'" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 40s
    expose:
      - "8080"
    networks:
      - paylock-network

  kong:
    image: kong:3.8
    container_name: paylock-kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml:ro
    depends_on:
      - paylock
    expose:
      - "8000"
      - "8001"
    networks:
      - paylock-network

  nginx:
    image: nginx:1.27-alpine
    container_name: paylock-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - kong
      - paylock
    ports:
      - "8088:80"
    networks:
      - paylock-network

#  portainer:
#    image: portainer/portainer-ce:latest
#    container_name: paylock-portainer
#    restart: unless-stopped
#    environment:
#      - TZ=UTC
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_data:/data
#    ports:
#      - "9000:9000"
#      - "9443:9443"
#    networks:
#      - paylock-network

#  uptime-kuma:
#    image: louislam/uptime-kuma:1
#    container_name: paylock-uptime-kuma
#    restart: unless-stopped
#    environment:
#      - TZ=UTC
#    volumes:
#      - uptime_kuma_data:/app/data
#    ports:
#      - "3001:3001"
#    networks:
#      - paylock-network

volumes:
  mysql-data:
  portainer_data:
  uptime_kuma_data:

networks:
  paylock-network:
    driver: bridge